// アプリケーション全体で使用するカラーパレット定数
export const COLOR_OPTIONS = [
  { title: 'プライマリー', value: 'primary' },
  { title: 'セカンダリー', value: 'secondary' },
  { title: '成功', value: 'success' },
  { title: '情報', value: 'info' },
  { title: '警告', value: 'warning' },
  { title: 'エラー', value: 'error' },
  { title: '赤', value: 'red' },
  { title: 'ピンク', value: 'pink' },
  { title: 'ローズ', value: 'rose' },
  { title: '紫', value: 'purple' },
  { title: 'ディープパープル', value: 'deep-purple' },
  { title: 'インディゴ', value: 'indigo' },
  { title: '青', value: 'blue' },
  { title: 'ライトブルー', value: 'light-blue' },
  { title: 'シアン', value: 'cyan' },
  { title: 'ティール', value: 'teal' },
  { title: '緑', value: 'green' },
  { title: 'ライトグリーン', value: 'light-green' },
  { title: 'ライム', value: 'lime' },
  { title: 'イエロー', value: 'yellow' },
  { title: 'アンバー', value: 'amber' },
  { title: 'オレンジ', value: 'orange' },
  { title: 'ディープオレンジ', value: 'deep-orange' },
  { title: 'ブラウン', value: 'brown' },
  { title: 'グレー', value: 'grey' },
  { title: 'ブルーグレー', value: 'blue-grey' },
] as const

export type ColorOption = typeof COLOR_OPTIONS[number]
